### ISSUE TITLE
contract - fields

### ISSUE THREAD

**Issue by mireille-raad** [OC-Bandung/birms-html#16]
We tried to do data statistics before to inform oc-explorer but we couldn't. Now that we have the OCDS json published, here are my questions about fields. I could mine the api, but that might be un-necessary load on the server ;p @bdgcoder feel free to answer things in the comments. Each checkbox item is one question. Sometimes it is long because I try to give description and detail.

**Common**
 
**Parties**

- [ ] In the data, how often are buyer and procurement entity the same? I am looking at sample json data and some are the same. How often is this true (few times, many times or most times)?

**Planning** - [ocds link](http://standard.open-contracting.org/latest/en/schema/reference/#planning)
- [ ] Are you publishing Rationale also known as ta_sasaran (Ur_Sasaran)? OCDS definition: The rationale for the procurement provided in free text. More detail can be provided in an attached document.
- [ ] Are you publishing "additionalProcurementCategories" - It would include the local categories in bandung. OCDS definition : additional procurement categories | Any additional categories which describe the objects of this contracting process, from the extendedProcurementCategory codelist. This is an open codelist. Local categories can be included in this list. 
 

 
**Milestone** - [ocds link](http://standard.open-contracting.org/latest/en/schema/reference/#milestone )

The current json that you have for milestone is as follow:

```
 {
     "id": 102,
      "title": "PENGUMUMAN_LELANG",
      "description": null,
       "dueDate": "2016-02-29T23:00:00+00:00",
        "dateMet": "2016-02-24T08:00:00+00:00",
       "status": "scheduled"
  }
```

In OCDS there is a field called  **code**. Here is the definition: Milestone codes can be used to track specific events that take place for a particular kind of contracting process. For example, a code of ‘approvalLetter’ could be used to allow applications to understand this milestone represents the date an approvalLetter is due or signed. Milestone codes is an open codelist, and codes should be agreed among data producers and the applications using that data.

In the contract page, we this timeline that is supposed to have the following dates: 
- HPS Issued
- DPA Issued
- SIRUP Application
- Tender Issued
- Invitation published
- Submission Deadline
- Award decision
- Contract Signing
- Commencement
- Completion

Old screenshot:
<img width="1386" alt="screen shot 2018-08-01 at 12 35 57 pm" src="https://user-images.githubusercontent.com/521705/43535310-99d0f534-9587-11e8-9db2-b25eeb0210b0.png">

So, titan, for the milestones above, can you add a new field called code, and put in it the default value "timeline"? 

The above json will become 
```
 {
     "id": 102,
      "title": "HPS Issued In bahasa",
      "code": "timeline", 
      "description": null,
      "dueDate": "2016-02-29T23:00:00+00:00",
       "dateMet": "2016-02-24T08:00:00+00:00",
       "status": "scheduled"
  }
```

I use the code: timeline to filter what I should show in the UI.

**Comment by mireille-raad** [comment]
Here are my notes about status:

- In getNonCompetitiveAward on [this line](https://github.com/OC-Bandung/newbirms/blob/%2315_json_for_a_single_contract_in_OCDS_format/app/Http/Controllers/ApiBIRMS_Contract.php#L416
 ) in your code, I can see $a->status assigned.
- In getCompetitiveAward on [this line ](https://github.com/OC-Bandung/newbirms/blob/b7aee0643b4fd16f87c8bd9d83338ee307142ef6/app/Http/Controllers/ApiBIRMS_Contract.php#L441) I can also see a status
- **Tender status is commented out on** [this line](https://github.com/OC-Bandung/newbirms/blob/b7aee0643b4fd16f87c8bd9d83338ee307142ef6/app/Http/Controllers/ApiBIRMS_Contract.php#L599) with the note ``` //$tender->status=$tleresults[0]->stat; //TODO: uncomment this after mapping done``` 

So, can we maybe un-comment  
``` //$tender->status=$tleresults[0]->stat; //TODO: uncomment this after mapping done```

Do we need to add status anywhere else?

For the UI, since we have status enough times, I will leave it there and just add if condition for the times it is not showing.

**Comment by mireille-raad** [comment]
Here are my notes about Rationale:

It doesn't seem to be in the code. I did a search a quick search. I think it is ta_sasaran (Ur_Sasaran) in the database. 

@bdgcoder  do you think you will have time to add it? or do i drop it from the UI?

**Comment by mireille-raad** [comment]
- add start date + end date in planning.
